  CLS
   PRINT "            ESCRITOR DE CARTAS DE AGRADECIMENTO"
   PRINT
   PRINT "NOME DE QUEM DEU O PRESENTE"
   INPUT D$
   PRINT "PRESENTE"
   INPUT P$
   PRINT "SEU NOME"
   INPUT N$
   CLS
   PRINT
    PRINT
    PRINT D$; ":"
    PRINT
    PRINT "Muito obrigado por me enviar "; P$; "."
    PRINT "ê um ¢timo presente!"
    PRINT "Gostei muito e pretendo us†-lo sempre."
    PRINT
    PRINT "Um grande abraáo para vocà, "; D$
    PRINT "De seu amigo, "; N$

